export const TRACKS = [
    {
        title: 'death bed',
        artist: 'Powfu',
        artwork: require('./assets/album-arts/death-bed.jpg'),
        url: require('./assets/audio/1.mp3'),
        duration: 2 * 60 + 53,
        id: '1',
    },
    {
        title: 'bad liar',
        artist: 'Imagine Dragons',
        artwork: require('./assets/album-arts/bad-liar.jpg'),
        url: require('./assets/audio/5.mp3'),
        duration: 2 * 60,
        id: '2',
    },
    {
        title: 'faded',
        artist: 'Alan Walker',
        artwork: require('./assets/album-arts/faded.jpg'),
        url: require('./assets/audio/4.mp3'),
        duration: 3 * 60,
        id: '3',
    },
    {
        title: 'hate me',
        artist: 'Ellie Goulding',
        artwork: require('./assets/album-arts/hate-me.jpg'),
        url: require('./assets/audio/1.mp3'),
        duration: 2 * 60,
        id: '4',
    },
    {
        title: 'Solo',
        artist: 'Clean Bandit',
        artwork: require('./assets/album-arts/solo.jpg'),
        url: require('./assets/audio/2.mp3'),
        duration: 2 * 60,
        id: '5',
    },
    {
        title: 'without me',
        artist: 'Halsey',
        artwork: require('./assets/album-arts/without-me.jpg'),
        url: require('./assets/audio/3.mp3'),
        duration: 2 * 60,
        id: '6',
    },
];

